In [1]:
import torch

In [2]:
import torch.nn as nn

In [3]:
import numpy as np

In [4]:
def softmax(x):
    return np.exp(x)/np.sum(np.exp(x),axis=0)

In [5]:
x=np.array([2.0,1.0,0.1])

In [6]:
outputs=softmax(x)

In [8]:
print('softmax =',outputs)

softmax = [0.65900114 0.24243297 0.09856589]


In [9]:
x=torch.tensor([2.0,1.0,0.1])

In [11]:
outputs=torch.softmax(x,dim=0)

In [12]:
print(outputs)

tensor([0.6590, 0.2424, 0.0986])


In [13]:
loss=nn.CrossEntropyLoss()

In [25]:
y=torch.tensor([0])
y_pred_good=torch.tensor([[2.0,1.0,.1]])

In [26]:
y_pred_bad=torch.tensor([[.5,2.0,.3]])

In [27]:
l1=loss(y_pred_bad,y)
l2=loss(y_pred_good,y)
print(l1.item())
print(l2.item())

1.840616226196289
0.4170299470424652


In [30]:
_,preictions=torch.max(y_pred_good,1)

In [31]:
_,preictions1=torch.max(y_pred_bad,1)

In [32]:
preictions

tensor([0])

In [33]:
preictions1

tensor([1])